name: maize_gxe_prediction
channels:
  - anaconda
  - nvidia
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - comm=0.1.2=py38h06a4308_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.12.1=hca18f0e_1
  - icu=67.1=he1b5a44_0
  - idna=3.4=pyhd8ed1ab_0
  - ipykernel=6.19.2=py38hb070fc8_0
  - ipython=8.8.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - jupyter_client=7.4.8=py38h06a4308_0
  - jupyter_core=5.1.1=py38h06a4308_0
  - kiwisolver=1.4.4=py38h43d8883_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=py38h06a4308_0
  - openssl=3.1.1=hd590300_1
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.0.1=pyhd8ed1ab_0
  - platformdirs=2.5.2=py38h06a4308_0
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.16=he550d4f_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pyzmq=23.2.0=py38h6a678d5_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.31.0=pyhd8ed1ab_0
  - scipy=1.10.1=py38h59b608b_3
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=67.4.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.0=py38h31356c5_1
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tk=8.6.12=h27826a3_0
  - tornado=6.2=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing_extensions=4.6.0=pyha770c72_0
  - urllib3=2.0.2=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h2531618_0
  - pip:
    - alembic==1.9.4
    - cmaes==0.9.1
    - colorlog==6.7.0
    - greenlet==2.0.2
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - joblib==1.2.0
    - lightgbm==3.3.5
    - mako==1.2.4
    - markupsafe==2.1.2
    - numpy==1.24.2
    - optuna==3.1.0
    - packaging==23.0
    - pandas==1.5.3
    - pyarrow==11.0.0
    - pytz==2022.7.1
    - pyyaml==6.0
    - scikit-learn==1.2.1
    - sqlalchemy==2.0.4
    - threadpoolctl==3.1.0
    - tqdm==4.64.1
    - typing-extensions==4.5.0
    - zipp==3.15.0
prefix: /home/igorf/.conda/envs/maize_gxe_prediction
